### ISSUE TITLE
Explore Greenfinch APIs

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-rest-gw#100]
https://api.greenfinch.app/ and https://public.greenfinch.app/

What are the differences to REST gw, do we have anything missing, can any of REST gw APIs be improved?

**Comment by roman-khimov** [comment]
IIUC there are some major differences (bearer token handling?) that can't be changed, so it'd be nice to understand the best use case scenarios for both of them.

**Comment by smallhive** [comment]
I looked at these links and the functionality is quite close to the current HTTP-GW. But Greenfinch API has a method for object deleting
