### ISSUE TITLE
Some integration tests with AIO 0.38.0 fails

### ISSUE THREAD

**Issue by smallhive** [nspcc-dev/neofs-rest-gw#103]
If integration tests start with AIO 0.38.0, some tests fail with _missing homomorphic payload checksum_.

## Current Behavior
Tests fail with _missing homomorphic payload checksum_

## Expected Behavior
All tests passed

## Possible Solution
I consider the node should manage this situation

## Steps to Reproduce

1. Remove existing version and leave only `0.38.0` [here](https://github.com/nspcc-dev/neofs-rest-gw/blob/2f21d71e0ba0617ff1600387deeccba07d11784f/cmd/neofs-rest-gw/integration_test.go#L101)
2. Run integration tests

## Context
AIO 0.37 and 0.38 have some fixes about container starts. This allows us to remove _force ticks_ in tests.

## Regression
I think so. The error message comes to us from [node](https://github.com/nspcc-dev/neofs-node/commit/3de479ac622abe8e9e954c70b338f49b14b0f39d).
AIO 0.38.0 uses node 0.102.

**Comment by carpawell** [comment]
BTW, want to mention that `0.102.0` does not relate to any NeoFS component, I think you meant `neo-go` but it is a different story and it is not involved in object problems usually. JFYI.
