### ISSUE TITLE
Upgrade to OpenAPI V3

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-rest-gw#121]
OpenAPI `3.0` was released more than 6 years ago, and it's latest revision `3.1.0` was released almost 3 years ago. I think enough time has passed for an update, and afaik we are not burdened to support `2.X`

within this issue, first of all, it is proposed to prepare migration TODO list for the current [API](https://github.com/nspcc-dev/neofs-rest-gw/blob/master/spec/rest.yaml) and analyze potential impact

see also:
* https://swagger.io/specification/ (refers to `3.1.0` in Dec2023)
* https://github.com/OAI/OpenAPI-Specification/releases
* https://swagger.io/blog/news/whats-new-in-openapi-3-0/

**Comment by roman-khimov** [comment]
See https://github.com/nspcc-dev/neofs-rest-gw/pull/127#discussion_r1464529351 also.
