### ISSUE TITLE
Not possible to assign few operations for one token

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/neofs-rest-gw#131]
## Current Behavior
When I try to assign multiple operations to one token I get an error:
- `[{"container":{"verb":"SETEACL"}},{"container":{"verb":"DELETE"}}]` -> `duplicated token name ''`
- `[{"container":{"verb":["SETEACL", "DELETE"]}}]` -> `parsing tokens body from \"\" failed, because json: cannot unmarshal array into Go struct field Rule.container.verb of type models.Verb`

## Expected Behavior
Allow multiple transactions to be assigned to a single token

## Context
We need to reduce the number of tokens in the panel https://github.com/nspcc-dev/panel-fs-neo-org/issues/126

**Comment by roman-khimov** [comment]
These are not transactions, but rather rules.
