### ISSUE TITLE
In some cases strange JSON is returned instead of object data

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-rest-gw#143]
## Current Behavior
Getting some object via CID/OID may result in
```
HTTP request sent, awaiting response... 200 OK
Length: 4674727 (4.5M) [image/png]
Saving to: ‘Gv4wff8xG6A12nTQdpZzX1qPUgdAZFGYBvjS6o7u6qvg’
...
2024-02-12 18:51:27 (8.35 MB/s) - Connection closed at byte 25. Retrying.
```
The contents of the file is
```
{"Reader":{},"Closer":{}}
```

## Expected Behavior
File fetched via gw.

## Possible Solution
It's obviously related to `readCloser`, but I can't figure out how exactly and why it happens on some gateways (for every request until restart) and not the others.

## Context
The object in question doesn't have any Content-Type in its meta, so it's autodetected.

## Your Environment
* Version of the product used: 0.7.0

**Comment by roman-khimov** [comment]
Notice also that `Length: 4674727 (4.5M)` is correct, which means that storage node does return something correct for the object.

**Comment by roman-khimov** [comment]
But maybe it's just a nil `Payload io.ReadCloser`.

**Comment by roman-khimov** [comment]
`JSONProducer` might be involved in this, but why only in some cases?

**Comment by roman-khimov** [comment]
When it happens
```
wget localhost:8880/v1/get/mwa6Fbia757WvezeeaLfvDsA7hMhdv7bDwN34hBhc97/Gv4wff8xG6A12nTQdpZzX1qPUgdAZFGYBvjS6o7u6qvg
```
yields bad result, while
```
wget --header="accept: application/octet-stream" localhost:8880/v1/get/mwa6Fbia757WvezeeaLfvDsA7hMhdv7bDwN34hBhc97/Gv4wff8xG6A12nTQdpZzX1qPUgdAZFGYBvjS6o7u6qvg
```
works just fine. It's certainly related to multiple `produces` defined for our APIs. Likely leaving just one can solve it. It at the same time is not entirely correct.

Also
```
wget --header="accept: application/json" localhost:8880/v1/get/mwa6Fbia757WvezeeaLfvDsA7hMhdv7bDwN34hBhc97/Gv4wff8xG6A12nTQdpZzX1qPUgdAZFGYBvjS6o7u6qvg
```
reproduces this even on the good gw.
```

**Comment by tatiana-nspcc** [comment]
We actually always use only 1 producer: - application/octet-stream. The others were added for the sake of documentation aesthetics. I suggest removing them and describing in the text that the returned content-type can be different.

**Comment by roman-khimov** [comment]
Let's have `application/octet-stream` until we resolve it properly with #121.
