### ISSUE TITLE
Run REST tests from neofs-testcases for PRs and master pushes

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-rest-gw#185]
## Is your feature request related to a problem? Please describe.
I'm always frustrated when we don't use all of our testing capabilities. We have neofs-testcases, there are REST tests there, but we don't run them regularly for the gateway.

## Describe the solution you'd like
Add them here similar to how S3 gateway runs a subset of S3 tests.

**Comment by evgeniiz321** [comment]
closed by https://github.com/nspcc-dev/neofs-rest-gw/pull/194
