### ISSUE TITLE
rest gw doesn't take into account updated network settings

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-rest-gw#247]
https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/518-1726084393/index.html#suites/820837d46c5808d6efecf59b97ab3206/ad221a173e92ac0d/

1. Set HomomorphicHashingDisabled=true
2. Create new container via neofs-cli - success
3. Try to create new container via rest-gw - failed:

ir logs:
```
2024-09-11T18:38:54.035Z	error	container/process_container.go:46	put container check failed	{"error": "incorrect homomorphic hashing setting: network setting: true, container setting: false"}
```

Either this setting should be available via rest gw api to set, or it should be taken from the network.

**Comment by roman-khimov** [comment]
REST can't get settings for each request, it caches them. But this can lead to problems, true. Maybe we can cache them just for an epoch.
