### ISSUE TITLE
Evaluate http/rest gw differences

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-rest-gw#99]
Compare API abilities, check if REST can substitute HTTP completely, what's missing for that and what's going to be the difference (simple GET/PUT should look similar), what migrations would be needed. You can create a document right here.

**Comment by roman-khimov** [comment]
Pay special attention to attribute handling and headers, also things like zip archives or auth tokens.

**Comment by smallhive** [comment]
The comparison result is located [here](https://docs.google.com/document/d/1MkCkyjuEIB1GedmEcIHOTAYQ2hmbZpcRq2RkmoR_U_0/edit)

**Comment by roman-khimov** [comment]
Refs. #109, #110, #111, #112.
